@startuml
actor Bob
Bob -> UI: Input "calories in" command
activate UI

UI -> UI: handleCaloriesInput(String, CalorieList)
activate UI

UI -> CalorieList: addEntry(String)
activate CalorieList

CalorieList -> ParserCalories: parseCaloriesInput(String, int)
activate ParserCalories

ParserCalories -> ParserCalories : makeNewInputEntry(int, String, int, String)
activate ParserCalories

return InputEntry
return InputEntry

CalorieList -> CalorieList: calorieArrayList.add(InputEntry)
activate CalorieList
return



alt calorieArrayList not sorted by date in ascending order
    CalorieList -> CalorieList : sortEntriesByDate()
    activate CalorieList
    return
end

CalorieList -> CalorieList: updateFile()
activate CalorieList

CalorieList -> CaloriesFileHandler : writeEntries(ArrayList<Entry>)
activate CaloriesFileHandler
CaloriesFileHandler -> CaloriesFileHandler : writeToFile(String)
activate CaloriesFileHandler
return
return

return
return
return
return New InputEntry added

@enduml