@startuml

rectangle HydrationList
rectangle HydrationEntry

rectangle Entry
rectangle HydrationFileHandler
rectangle Ui
rectangle ParserHydration

HydrationList --> "*" Entry
HydrationList ---> "1" HydrationFileHandler
HydrationList --[dotted]> ParserHydration

Ui -[dotted]> HydrationList

HydrationEntry --|> Entry

ParserHydration -[dotted]-> HydrationEntry

@enduml