@startuml

rectangle SleepList
rectangle SleepEntry

rectangle Entry
rectangle SleepFileHandler
rectangle Ui
rectangle ParserSleep

SleepList --> "*" Entry
SleepList ---> "1" SleepFileHandler
SleepList --[dotted]> ParserSleep

Ui -[dotted]> SleepList

SleepEntry --|> Entry

ParserSleep -[dotted]-> SleepEntry

@enduml