@startuml

rectangle User

rectangle UserFileHandler

rectangle ParserUser

rectangle UserGoals

rectangle HydrationList
rectangle CaloriesList
rectangle SleepList

User ---> "1" UserFileHandler
User --[dotted]> ParserUser

User <-[dotted]> UserGoals

UserGoals --[dotted]> HydrationList
UserGoals --[dotted]> CaloriesList
UserGoals --[dotted]> SleepList

@enduml