@startuml

skinparam classAttributeIconSize 0

class LifeTrack {
    +main(args: String[]): void
}

package ui {
    class Ui {
        + readUserInput(calorieList: calories.CalorieList, ...... ) : void
        + handleUserInput(line: String, calorieLIst: CalorieList, ......): void
        + handleCaloriesInput(line: String, calorieList: calories.CalorieList): void
    }
    class CalorieListUi {
            + calorieListHeader(): void
            + emptyListMessage(): void
            + inputCalorieListHeader(): void
            + outputCalorieListHeader(): void
    }
}

package calories {
    package calorielist {
        class CalorieList {
            - ArrayList<Entry> calorieArrayList
            + printCalorieList(): void
            + printCalorieInflow(): void
            + printCalorieOutflow(): void
        }

    }
}

hide circle
LifeTrack --> calories.calorielist.CalorieList
LifeTrack -[dotted]-> ui.Ui
ui.Ui -[dotted]-> calories.calorielist.CalorieList
CalorieList -[dotted]-> CalorieListUi

@enduml


